version: '3.4'

services:
  client:
    build:
      context: .
      target: client
    volumes:
      - ./client:/app
    command: npm start
    ports:
      - "8080:8080"
  server:
    build: .
    ports:
      - "9090:9090"
